# "*Arr" or "*Arrs" are designed to automatically grab, sort, organize, and monitor your Music, Movie, E-Book, or TV Show collections for Lidarr, Radarr, Readarr, Sonarr, and Whisparr; and to manage your indexers and keep them in sync with the aforementioned apps for Prowlarr.
# https://wiki.servarr.com/
---
version: "3.4"

services:
# FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection.
# https://github.com/FlareSolverr/FlareSolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    user: '1000:1000'
    environment:
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/flaresolverr:/config
    # ports:
    #   - 8191:8191
    restart: unless-stopped

# Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps.
# https://github.com/Prowlarr/Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/prowlarr:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped

# Sonarr is a PVR for Usenet and BitTorrent users.
# https://github.com/Sonarr/Sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${config_dir}/sonarr:/config
      - ${data_dir}:/data
    # ports:
    #   - 8989:8989
    restart: unless-stopped

# Radarr is a movie collection manager for Usenet and BitTorrent users.
# https://github.com/Radarr/Radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${config_dir}/radarr:/config
      - ${data_dir}:/data
    # ports:
    #   - 7878:7878
    restart: unless-stopped

# Jellyseerr is a free and open source software application for managing requests for your media library.
# https://github.com/Fallenbagel/jellyseerr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    user: '1000:1000'
    environment:
      - TZ=${time_zone}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${config_dir}/jellyseerr:/app/config
    # ports:
    #   - 5055:5055
    restart: unless-stopped

# AIO Prometheus Exporter for Sonarr, Radarr, Lidarr, Prowlarr, Readarr, Bazarr and Sabnzbd
# https://github.com/onedr0p/exportarr
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.6.0
    container_name: sonarr-exporter
    user: '1000:1000'
    command: ["sonarr"]
    environment:
      - TZ=${time_zone}
      - PORT=9707
      - URL=http://sonarr:8989
      - APIKEY=${sonarr_api_key}
    # ports:
    #   - 9707:9707
    restart: unless-stopped

# AIO Prometheus Exporter for Sonarr, Radarr, Lidarr, Prowlarr, Readarr, Bazarr and Sabnzbd
# https://github.com/onedr0p/exportarr
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v1.6.0
    container_name: radarr-exporter
    user: '1000:1000'
    command: ["radarr"]
    environment:
      - TZ=${time_zone}
      - PORT=9708
      - URL=http://radarr:7878
      - APIKEY=${radarr_api_key}
    # ports:
    #   - 9708:9708
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
