# A tunneling daemon that proxies traffic from the Cloudflare network to your origins.
# https://github.com/cloudflare/cloudflared

---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TUNNEL_TOKEN=${cloudflare_token}
    command: tunnel --no-autoupdate run
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
