# The Ultimate Homepage for your Homelab.
version: "3.8"

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    # ports:
    #   - 4000:80
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network