# Filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files.
# https://github.com/filebrowser/filebrowser
---
version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${data_dir}:/data
      - ${config_dir}/filebrowser:/config
    ports:
      - 9003:8080
    restart: unless-stopped
