# Filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files.
# https://github.com/filebrowser/filebrowser

# NO LONGER MAINTAINED
# ---
# services:
#   filebrowser:
#     image: hurlenko/filebrowser:latest
#     container_name: filebrowser
#     user: "1000:1000"
#     environment:
#       - TZ=${time_zone}
#     volumes:
#       - ${data_dir}:/data
#       - ${config_dir}/filebrowser:/config
#     # ports:
#     #   - 9003:8080
#     restart: unless-stopped

# Web-based file manager with source configuration, modern authentication, office support, and lightning-fast search.
# https://filebrowserquantum.com/en/
---
services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: filebrowser
    user: "1000:1000"
    environment:
      - TZ=${time_zone}
    volumes:
      - ${data_dir}:/data
      - ${config_dir}/filebrowserquantum:/home/filebrowser/data
    # ports:
    #   - 9003:80
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
