# Freshrss is a free, self-hostable aggregator for rss feeds.
# https://hub.docker.com/r/linuxserver/freshrss
---
version: "2.1"

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/freshrss:/config
    # ports:
    #   - 9012:80
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
