# Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored.
# https://github.com/grafana/grafana
---
version: "3"

services:
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    user: "1000:1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_pass}
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource, grafana-piechart-panel, flant-statusmap-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/grafana/data:/var/lib/grafana
      # - ${config_dir}/grafana/config:/etc/grafana
    # ports:
    #   - 3000:3000
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
