# Homarr - a sleek, modern dashboard that puts all of your apps and services at your fingertips.
# https://github.com/ajnart/homarr
---
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    user: "1000:1000"
    environment:
      - TZ=${time_zone}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${config_dir}/homarr/config:/app/data/configs
      - ${config_dir}/homarr/icons:/app/public/icons
      - ${config_dir}/homarr/data:/data
    # ports:
    #   - 9013:7575
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
