# Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media.
# https://github.com/jellyfin/jellyfin
---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    group_add:
      - "993" # Change this to match your "render" host group id
    volumes:
      - ${data_dir}/tvshows:/data/tvshows
      - ${data_dir}/movies:/data/movies
      - ${config_dir}/jellyfin:/config
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
