# Librespeed is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers.
# https://hub.docker.com/r/linuxserver/librespeed
---
version: "2.1"

services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/librespeed:/config
    ports:
      - 9008:80
    restart: unless-stopped
