# An open-source, self-hosted note-taking solution designed for seamless deployment and multi-platform access.
# https://github.com/usememos/memos
---
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/memos:/var/opt/memos
    # ports:
    #   - 5230:5230
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
