# Eclipse Mosquitto is an open source (EPL/EDL licensed) message broker that implements the MQTT protocol
# https://github.com/eclipse/mosquitto
---
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: "1000:1000"
    environment:
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/mosquitto:/mosquitto
    ports:
      - 1883:1883
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
