# self-hosted collaboration solution
version: '3'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    # ports:
    #   - 8888:80
    volumes:
      - ${base_dir}/nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${mysql_root_pass}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=${nextcloud_user}
      - NEXTCLOUD_ADMIN_PASSWORD=${nextcloud_pass}
      - NEXTCLOUD_TRUSTED_DOMAINS${nextcloud_domains}
      - NEXTCLOUD_UPDATE=1
      - TZ=Europe/Vilnius
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network