# SpeedTest by OpenSpeedTest™ is a Free and Open-Source HTML5 Network Performance Estimation Tool.
# https://github.com/openspeedtest/Speed-Test
---
services:
  speedtest:
    image: openspeedtest/latest
    container_name: speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    # ports:
    #   - 9009:3000
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
