# Agent for portainer container management tool.
# https://docs.portainer.io/admin/environments/add/docker/agent
---
version: "3"

services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always
