# Application that monitors the performance and uptime of your internet connection.
# https://github.com/alexjustesen/speedtest-tracker
---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID= 1000
      - PGID=1000
      - DISPLAY_TIMEZONE=${time_zone}
      - APP_KEY=${st_app_key}
      - APP_URL=${st_app_url}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 * * * *
      - ADMIN_EMAIL=${st_admin_email}
      - ADMIN_PASSWORD=${st_admin_password}
    volumes:
      - ${config_dir}/speedtest-tracker:/config
    # ports:
    #   - 6080:80
    #   - 5443:443
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
