---
services:
  # TubeSync is a PVR (personal video recorder) for YouTube.
  # https://github.com/meeb/tubesync
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/tubesync:/config
      - ${data_dir}/podcasts:/downloads
    # ports:
    #   - 9006:4848
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
