# Uptime Kuma is an easy-to-use self-hosted monitoring tool.
# https://github.com/louislam/uptime-kuma
---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${time_zone}
    volumes:
      - ${config_dir}/uptime-kuma:/app/data
    # ports:
    #   - 9010:3001
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network
