# Gitea is a lightweight DevOps platform.
version: "2"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - TZ=Europe/Vilnius
    volumes:
      - "${base_dir}/gitea:/data:Z"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      # - 3000:3000
      - 2222:22
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network