# Gitea is a lightweight DevOps platform.
version: "3"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    volumes:
      - "${base_dir}/gitea:/data:Z"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "2222:22"
      # - "3000:3000"
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy-network