# Docker container for managing Nginx proxy hosts with a simple, powerful interface
version: "3"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - "${base_dir}/npm/data:/data"
    ports:
      - 80:80
      - 81:81
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/Vilnius
      - DISABLE_IPV6=true
    restart: unless-stopped

networks:
  default:
    external:
      name: docker_default