# Grafana dashboard for raspberry pi.
# Based on https://github.com/novaspirit/Docker-Raspberry-PI-Monitoring
# Expanded with https://github.com/f5AFfMhv/emonesp-grafana
version: "3"

services:
  cadvisor:
    devices:
      - /dev/kmsg
    image: zcube/cadvisor:latest
    ipc: shareable
    environment:
      - TZ=Europe/Vilnius
    networks:
      - rpimonitor_default
    privileged: true
    restart: unless-stopped
    security_opt:
      - label=disable
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  grafana:
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - TZ=Europe/Vilnius
    user: "${UID}:${GID}"
    image: grafana/grafana:latest
    networks:
      - rpimonitor_default
    ports:
      - 8200:3000
    restart: unless-stopped
    volumes:
      - /mnt/data/rpi-monitoring/grafana/data:/var/lib/grafana
      - /mnt/data/rpi-monitoring/grafana/provisioning:/etc/grafana/provisioning

  node-exporter:
    image: prom/node-exporter:latest
    environment:
      - TZ=Europe/Vilnius
    networks:
      - rpimonitor_default
    restart: unless-stopped

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
    user: "${UID}:${GID}"
    image: prom/prometheus:latest
    networks:
      - rpimonitor_default
    restart: unless-stopped
    ports:
      - 8203:9090
    volumes:
      - /mnt/data/rpi-monitoring/prometheus/data:/prometheus
      - /mnt/data/rpi-monitoring/prometheus/config:/etc/prometheus/
    environment:
      - TZ=Europe/Vilnius
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  mosquitto:
    user: "${UID}:${GID}"
    image: eclipse-mosquitto:latest
    volumes:
      - /mnt/data/rpi-monitoring/mosquitto:/mosquitto
    environment:
      - TZ=Europe/Vilnius
    ports:
      - 1883:1883
    networks:
      - rpimonitor_default
    restart: unless-stopped

  mqtt2prometheus:
    user: "${UID}:${GID}"
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    environment:
      - TZ=Europe/Vilnius
    networks:
      - rpimonitor_default
    restart: unless-stopped
    volumes:
      - /mnt/data/rpi-monitoring/mqtt2prometheus/prometheus2mqtt_config.yaml:/config.yaml

networks:
  rpimonitor_default:
    external: true
