# Seafile is an open source file sync&share solution
version: '2.0'

services:
  mariadb:
    image: mariadb:10.5
    volumes:
      - "/mnt/data/seafile/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_pass}
      - MYSQL_LOG_CONSOLE=true
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/Vilnius
    restart: unless-stopped
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6
    entrypoint: memcached -m 256
    restart: unless-stopped
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    volumes:
      - "/mnt/data/seafile/data:/shared"
    ports:
      - "8273:80"
      # - "443:443"  # If https is enabled, cancel the comment.
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=${mysql_root_pass}
      - SEAFILE_ADMIN_EMAIL=me@example.com
      - SEAFILE_ADMIN_PASSWORD=${admin_pass}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.pi.home.lab
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/Vilnius
    restart: unless-stopped
    depends_on:
      - mariadb
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net: