# Cloud-native application proxy.
version: "3.3"

services:
  traefik:
    image: traefik:v2.6
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/Vilnius
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "82:80"
      - "8001:8080"
    restart: unless-stopped